export type StaticText = {
  [key: string]: {
    [key: string]: string;
  };
};

export const staticText: StaticText = {
  pl: {
    banerTitle: "Odkryj Świat Tarota",
    banerDesc: "Zdobądź Wgląd w Twoją Przyszłość!",
    banerButton: "Wejdź",
    pageName: "Aurum Tarot",
    pageLanguage: "Wybierz język",
    frontPageDescription: `Witaj w fascynującym świecie Tarota - tajemniczej sztuki odczytywania kart, która jest zarówno źródłem mądrości, jak i inspiracją do odkrywania mistycyzmu. Nasza strona zaprasza Cię do głębokiej podróży przez karty Tarota, gdzie archetypy, symbole i intuicja łączą się w jedno, by rzucić światło na przeszłość, teraźniejszość i przyszłość.
        Tarot to narzędzie, które przekracza granice czasu i przestrzeni. To magiczne karty, które pomagają nam lepiej zrozumieć siebie i otaczający nas świat. Jako przewodnicy na tej mistycznej drodze, jesteśmy tutaj, by pomóc Ci odkryć ukryte tajemnice swojego życia oraz lepiej zrozumieć to, co przynosi przyszłość.
        Przyjrzyj się uważnie kartom, zgłębiaj ich znaczenie, a w miarę jak poznasz tę sztukę, zobaczysz, jak można ją wykorzystać do przewidywania przyszłości. Tarot to lustrzane odbicie twojego wnętrza i mistyczna mapa, która pomoże Ci w nawigowaniu przez nieznane lądy.
            `,
    cardTypeGame: "Rozkład kart tarota",
    cardTypeSing: "Karta dnia dla znaków zodiaku",
    cardSingTitleLine1: "Karta dnia tarot",
    cardSingTitleLine2: " dla znaku zodiaku ",
    cardSingTitleLine3: " na dzień  ",
    cardSingLove: "Miłość",
    cardSingHealt: "Zdrowie",
    cardSingWork: "Praca",
    cardgamesDescription: `Przed przystąpieniem do rozkładania kart należy się wyciszyć można
        zapalić świeczkę i zastanowić nad zadanym pytaniem.`,
    cardgamesActionButton: "Rozłóż karty",
  },
  en: {
    "banerTitle": "Discover the World of Tarot",
    "banerDesc": "Gain Insight into Your Future!",
    "banerButton": "Enter",
    "pageName": "Aurum Tarot",
    "pageLanguage": "Choose Language",
    "frontPageDescription": "Welcome to the fascinating world of Tarot - the mysterious art of card reading that serves as both a source of wisdom and inspiration for exploring mysticism. Our site invites you on a profound journey through Tarot cards, where archetypes, symbols, and intuition come together to shed light on the past, present, and future.\nTarot is a tool that transcends time and space. These magical cards help us better understand ourselves and the world around us. As guides on this mystical path, we are here to help you uncover the hidden secrets of your life and gain a better understanding of what the future holds.\nExamine the cards carefully, delve into their meanings, and as you learn this art, you will see how it can be used to predict the future. Tarot is a mirror reflection of your inner self and a mystical map to navigate through unknown lands.",
    "cardTypeGame": "Tarot Card Spread",
    "cardTypeSing": "Daily Card for Zodiac Signs",
    "cardSingTitleLine1": "Tarot Card of the Day",
    "cardSingTitleLine2": " for Zodiac Sign ",
    "cardSingTitleLine3": " for the Day ",
    "cardSingLove": "Love",
    "cardSingHealt": "Health",
    "cardSingWork": "Work",
    "cardgamesDescription": "Before you start the card spread, it is important to calm your mind. You may light a candle and reflect on the question you wish to ask.",
    "cardgamesActionButton": "Spread the Cards"
  },
  de: {
    "banerTitle": "Entdecke die Welt des Tarots",
    "banerDesc": "Gewinne Einblick in Deine Zukunft!",
    "banerButton": "Eintritt",
    "pageName": "Aurum Tarot",
    "pageLanguage": "Sprache wählen",
    "frontPageDescription": "Willkommen in der faszinierenden Welt des Tarots - der geheimnisvollen Kunst des Kartenlesens, die sowohl eine Quelle der Weisheit als auch eine Inspiration zur Erkundung des Mystischen ist. Unsere Seite lädt dich zu einer tiefen Reise durch die Tarotkarten ein, bei der Archetypen, Symbole und Intuition sich vereinen, um Licht auf Vergangenheit, Gegenwart und Zukunft zu werfen.\nTarot ist ein Werkzeug, das die Grenzen von Zeit und Raum überschreitet. Diese magischen Karten helfen uns, uns selbst und die Welt um uns herum besser zu verstehen. Als Führer auf diesem mystischen Weg sind wir hier, um dir zu helfen, die verborgenen Geheimnisse deines Lebens zu entdecken und ein besseres Verständnis dafür zu bekommen, was die Zukunft bereithält.\nBetrachte die Karten sorgfältig, vertiefe dich in ihre Bedeutungen, und während du diese Kunst erlernst, wirst du sehen, wie sie zur Vorhersage der Zukunft genutzt werden kann. Tarot ist ein Spiegelbild deines Inneren und eine mystische Karte, die dir hilft, durch unbekannte Länder zu navigieren.",
    "cardTypeGame": "Tarot-Kartenlegung",
    "cardTypeSing": "Tageskarte für Sternzeichen",
    "cardSingTitleLine1": "Tarotkarte des Tages",
    "cardSingTitleLine2": " für das Sternzeichen ",
    "cardSingTitleLine3": " für den Tag ",
    "cardSingLove": "Liebe",
    "cardSingHealt": "Gesundheit",
    "cardSingWork": "Arbeit",
    "cardgamesDescription": "Bevor du mit dem Legen der Karten beginnst, ist es wichtig, deinen Geist zu beruhigen. Du kannst eine Kerze anzünden und über die Frage nachdenken, die du stellen möchtest.",
    "cardgamesActionButton": "Karten legen"
  },
  fr: {
    "banerTitle": "Découvrez le Monde du Tarot",
    "banerDesc": "Obtenez un Aperçu de Votre Avenir !",
    "banerButton": "Entrer",
    "pageName": "Aurum Tarot",
    "pageLanguage": "Choisissez la Langue",
    "frontPageDescription": "Bienvenue dans le monde fascinant du Tarot - l'art mystérieux de la lecture des cartes qui est à la fois une source de sagesse et une inspiration pour explorer le mysticisme. Notre site vous invite à un voyage profond à travers les cartes du Tarot, où archétypes, symboles et intuition se rejoignent pour éclairer le passé, le présent et l'avenir.\nLe Tarot est un outil qui transcende le temps et l'espace. Ces cartes magiques nous aident à mieux comprendre nous-mêmes et le monde qui nous entoure. En tant que guides sur ce chemin mystique, nous sommes ici pour vous aider à découvrir les secrets cachés de votre vie et à mieux comprendre ce que l'avenir vous réserve.\nExaminez les cartes attentivement, plongez dans leurs significations, et à mesure que vous apprenez cet art, vous verrez comment il peut être utilisé pour prédire l'avenir. Le Tarot est un reflet de votre intérieur et une carte mystique pour naviguer à travers des territoires inconnus.",
    "cardTypeGame": "Étendue de Cartes de Tarot",
    "cardTypeSing": "Carte du Jour pour les Signes du Zodiaque",
    "cardSingTitleLine1": "Carte de Tarot du Jour",
    "cardSingTitleLine2": " pour le Signe du Zodiaque ",
    "cardSingTitleLine3": " pour le Jour ",
    "cardSingLove": "Amour",
    "cardSingHealt": "Santé",
    "cardSingWork": "Travail",
    "cardgamesDescription": "Avant de commencer le tirage des cartes, il est important de calmer votre esprit. Vous pouvez allumer une bougie et réfléchir à la question que vous souhaitez poser.",
    "cardgamesActionButton": "Tirer les Cartes"
  },
  es: {
    "banerTitle": "Descubre el Mundo del Tarot",
    "banerDesc": "¡Obtén Perspectiva sobre tu Futuro!",
    "banerButton": "Entrar",
    "pageName": "Aurum Tarot",
    "pageLanguage": "Selecciona Idioma",
    "frontPageDescription": "Bienvenido al fascinante mundo del Tarot: el arte misterioso de la lectura de cartas que es tanto una fuente de sabiduría como una inspiración para explorar el misticismo. Nuestro sitio te invita a un viaje profundo a través de las cartas del Tarot, donde arquetipos, símbolos e intuición se unen para arrojar luz sobre el pasado, el presente y el futuro.\nEl Tarot es una herramienta que trasciende el tiempo y el espacio. Estas cartas mágicas nos ayudan a comprendernos mejor a nosotros mismos y al mundo que nos rodea. Como guías en este camino místico, estamos aquí para ayudarte a descubrir los secretos ocultos de tu vida y entender mejor lo que el futuro te depara.\nExamina las cartas con cuidado, profundiza en sus significados y, a medida que aprendas este arte, verás cómo se puede utilizar para predecir el futuro. El Tarot es un reflejo de tu interior y un mapa místico para navegar por territorios desconocidos.",
    "cardTypeGame": "Lectura de Cartas de Tarot",
    "cardTypeSing": "Carta del Día para Signos del Zodiaco",
    "cardSingTitleLine1": "Carta de Tarot del Día",
    "cardSingTitleLine2": " para el Signo del Zodiaco ",
    "cardSingTitleLine3": " para el Día ",
    "cardSingLove": "Amor",
    "cardSingHealt": "Salud",
    "cardSingWork": "Trabajo",
    "cardgamesDescription": "Antes de comenzar a desplegar las cartas, es importante calmar tu mente. Puedes encender una vela y reflexionar sobre la pregunta que deseas hacer.",
    "cardgamesActionButton": "Desplegar las Cartas"
  },
  nl: {
    "banerTitle": "Ontdek de Wereld van Tarot",
    "banerDesc": "Krijg Inzicht in je Toekomst!",
    "banerButton": "Betreed",
    "pageName": "Aurum Tarot",
    "pageLanguage": "Kies Taal",
    "frontPageDescription": "Welkom in de fascinerende wereld van Tarot - de mysterieuze kunst van het kaarten lezen, die zowel een bron van wijsheid als een inspiratie is voor het verkennen van mystiek. Onze site nodigt je uit voor een diepgaande reis door de Tarotkaarten, waar archetypen, symbolen en intuïtie samenkomen om licht te werpen op het verleden, het heden en de toekomst.\nTarot is een hulpmiddel dat de grenzen van tijd en ruimte overschrijdt. Deze magische kaarten helpen ons om onszelf en de wereld om ons heen beter te begrijpen. Als gidsen op dit mystieke pad zijn we hier om je te helpen de verborgen geheimen van je leven te ontdekken en een beter begrip te krijgen van wat de toekomst voor je in petto heeft.\nBestudeer de kaarten zorgvuldig, verdiep je in hun betekenissen, en terwijl je deze kunst leert, zul je zien hoe het kan worden gebruikt om de toekomst te voorspellen. Tarot is een spiegel van je innerlijke zelf en een mystieke kaart om door onbekende gebieden te navigeren.",
    "cardTypeGame": "Tarotkaartenlegging",
    "cardTypeSing": "Dagelijkse Kaart voor Sterrenbeelden",
    "cardSingTitleLine1": "Tarotkaart van de Dag",
    "cardSingTitleLine2": " voor Sterrenbeeld ",
    "cardSingTitleLine3": " voor de Dag ",
    "cardSingLove": "Liefde",
    "cardSingHealt": "Gezondheid",
    "cardSingWork": "Werk",
    "cardgamesDescription": "Voordat je begint met het leggen van de kaarten, is het belangrijk om je geest tot rust te brengen. Je kunt een kaars aansteken en nadenken over de vraag die je wilt stellen.",
    "cardgamesActionButton": "Leg de Kaarten"
  },
  it: {
    "banerTitle": "Scopri il Mondo dei Tarocchi",
    "banerDesc": "Ottieni una Visione sul Tuo Futuro!",
    "banerButton": "Entra",
    "pageName": "Aurum Tarot",
    "pageLanguage": "Scegli Lingua",
    "frontPageDescription": "Benvenuto nel affascinante mondo dei Tarocchi - l'arte misteriosa della lettura delle carte, che è sia una fonte di saggezza che un'ispirazione per esplorare il misticismo. Il nostro sito ti invita a un viaggio profondo attraverso le carte dei Tarocchi, dove archetipi, simboli e intuizione si uniscono per illuminare il passato, il presente e il futuro.\nIl Tarot è uno strumento che trascende il tempo e lo spazio. Queste carte magiche ci aiutano a comprendere meglio noi stessi e il mondo che ci circonda. Come guide su questo cammino mistico, siamo qui per aiutarti a scoprire i segreti nascosti della tua vita e comprendere meglio cosa riserva il futuro.\nEsamina attentamente le carte, approfondisci i loro significati e, man mano che apprendi quest'arte, vedrai come può essere utilizzata per prevedere il futuro. Il Tarot è un riflesso del tuo io interiore e una mappa mistica per navigare attraverso terre sconosciute.",
    "cardTypeGame": "Stesura delle Carte dei Tarocchi",
    "cardTypeSing": "Carta del Giorno per i Segni Zodiacali",
    "cardSingTitleLine1": "Carta dei Tarocchi del Giorno",
    "cardSingTitleLine2": " per il Segno Zodiacale ",
    "cardSingTitleLine3": " per il Giorno ",
    "cardSingLove": "Amore",
    "cardSingHealt": "Salute",
    "cardSingWork": "Lavoro",
    "cardgamesDescription": "Prima di iniziare a disporre le carte, è importante calmare la mente. Puoi accendere una candela e riflettere sulla domanda che desideri porre.",
    "cardgamesActionButton": "Disponi le Carte"
  },
};

export default staticText;
